//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP.Signicat.WebApi.SignicatPreProdPkg {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://id.signicat.com/definitions/wsdl/Packaging-v4", ConfigurationName="SignicatPreProdPkg.PackagingEndPoint")]
    public interface PackagingEndPoint {
        
        // CODEGEN: Generating message contract since the operation create-package is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PP.Signicat.WebApi.SignicatPreProdPkg.createpackageResponse1 createpackage(PP.Signicat.WebApi.SignicatPreProdPkg.createpackage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PP.Signicat.WebApi.SignicatPreProdPkg.createpackageResponse1> createpackageAsync(PP.Signicat.WebApi.SignicatPreProdPkg.createpackage request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://id.signicat.com/definitions/wsdl/Packaging-v4")]
    public partial class createpackagerequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private string serviceField;
        
        private string passwordField;
        
        private string validationpolicyField;
        
        private string packagingmethodField;
        
        private bool sendresulttoarchiveField;
        
        private object[] itemsField;
        
        public createpackagerequest() {
            this.sendresulttoarchiveField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
                this.RaisePropertyChanged("service");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("validation-policy", Order=3)]
        public string validationpolicy {
            get {
                return this.validationpolicyField;
            }
            set {
                this.validationpolicyField = value;
                this.RaisePropertyChanged("validationpolicy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("packaging-method", Order=4)]
        public string packagingmethod {
            get {
                return this.packagingmethodField;
            }
            set {
                this.packagingmethodField = value;
                this.RaisePropertyChanged("packagingmethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("send-result-to-archive", Order=5)]
        public bool sendresulttoarchive {
            get {
                return this.sendresulttoarchiveField;
            }
            set {
                this.sendresulttoarchiveField = value;
                this.RaisePropertyChanged("sendresulttoarchive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sdo", typeof(documentid), Order=6)]
        [System.Xml.Serialization.XmlElementAttribute("sdo-extended", typeof(sdoextended), Order=6)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="document-id", Namespace="https://id.signicat.com/definitions/wsdl/Packaging-v4")]
    public partial class documentid : object, System.ComponentModel.INotifyPropertyChanged {
        
        private archivedocumentid archivedocumentidField;
        
        private orderdocumentid orderdocumentidField;
        
        private sdsdocumentid sdsdocumentidField;
        
        private string uridocumentidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("archive-document-id", Order=0)]
        public archivedocumentid archivedocumentid {
            get {
                return this.archivedocumentidField;
            }
            set {
                this.archivedocumentidField = value;
                this.RaisePropertyChanged("archivedocumentid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("order-document-id", Order=1)]
        public orderdocumentid orderdocumentid {
            get {
                return this.orderdocumentidField;
            }
            set {
                this.orderdocumentidField = value;
                this.RaisePropertyChanged("orderdocumentid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sds-document-id", Order=2)]
        public sdsdocumentid sdsdocumentid {
            get {
                return this.sdsdocumentidField;
            }
            set {
                this.sdsdocumentidField = value;
                this.RaisePropertyChanged("sdsdocumentid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("uri-document-id", Order=3)]
        public string uridocumentid {
            get {
                return this.uridocumentidField;
            }
            set {
                this.uridocumentidField = value;
                this.RaisePropertyChanged("uridocumentid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="archive-document-id", Namespace="https://id.signicat.com/definitions/wsdl/Packaging-v4")]
    public partial class archivedocumentid : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://id.signicat.com/definitions/wsdl/Packaging-v4")]
    public partial class error : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="supplementary-data", Namespace="https://id.signicat.com/definitions/wsdl/Packaging-v4")]
    public partial class supplementarydata : object, System.ComponentModel.INotifyPropertyChanged {
        
        private documentid originaldocumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("original-document", Order=0)]
        public documentid originaldocument {
            get {
                return this.originaldocumentField;
            }
            set {
                this.originaldocumentField = value;
                this.RaisePropertyChanged("originaldocument");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="sds-document-id", Namespace="https://id.signicat.com/definitions/wsdl/Packaging-v4")]
    public partial class sdsdocumentid : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="order-document-id", Namespace="https://id.signicat.com/definitions/wsdl/Packaging-v4")]
    public partial class orderdocumentid : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requestidField;
        
        private string taskidField;
        
        private string documentidField;
        
        private System.Nullable<orderdocumenttype> typeField;
        
        public orderdocumentid() {
            this.typeField = orderdocumenttype.result;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("request-id", Order=0)]
        public string requestid {
            get {
                return this.requestidField;
            }
            set {
                this.requestidField = value;
                this.RaisePropertyChanged("requestid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("task-id", Order=1)]
        public string taskid {
            get {
                return this.taskidField;
            }
            set {
                this.taskidField = value;
                this.RaisePropertyChanged("taskid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("document-id", Order=2)]
        public string documentid {
            get {
                return this.documentidField;
            }
            set {
                this.documentidField = value;
                this.RaisePropertyChanged("documentid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<orderdocumenttype> type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="order-document-type", Namespace="https://id.signicat.com/definitions/wsdl/Packaging-v4")]
    public enum orderdocumenttype {
        
        /// <remarks/>
        source,
        
        /// <remarks/>
        result,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="sdo-extended", Namespace="https://id.signicat.com/definitions/wsdl/Packaging-v4")]
    public partial class sdoextended : object, System.ComponentModel.INotifyPropertyChanged {
        
        private documentid sdoField;
        
        private supplementarydata supplementarydataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public documentid sdo {
            get {
                return this.sdoField;
            }
            set {
                this.sdoField = value;
                this.RaisePropertyChanged("sdo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("supplementary-data", Order=1)]
        public supplementarydata supplementarydata {
            get {
                return this.supplementarydataField;
            }
            set {
                this.supplementarydataField = value;
                this.RaisePropertyChanged("supplementarydata");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://id.signicat.com/definitions/wsdl/Packaging-v4")]
    public partial class createpackageresponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private error errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public error error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createpackage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="create-package-request", Namespace="https://id.signicat.com/definitions/wsdl/Packaging-v4", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("create-package-request")]
        public PP.Signicat.WebApi.SignicatPreProdPkg.createpackagerequest createpackagerequest;
        
        public createpackage() {
        }
        
        public createpackage(PP.Signicat.WebApi.SignicatPreProdPkg.createpackagerequest createpackagerequest) {
            this.createpackagerequest = createpackagerequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createpackageResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="create-package-response", Namespace="https://id.signicat.com/definitions/wsdl/Packaging-v4", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("create-package-response")]
        public PP.Signicat.WebApi.SignicatPreProdPkg.createpackageresponse createpackageresponse;
        
        public createpackageResponse1() {
        }
        
        public createpackageResponse1(PP.Signicat.WebApi.SignicatPreProdPkg.createpackageresponse createpackageresponse) {
            this.createpackageresponse = createpackageresponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PackagingEndPointChannel : PP.Signicat.WebApi.SignicatPreProdPkg.PackagingEndPoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PackagingEndPointClient : System.ServiceModel.ClientBase<PP.Signicat.WebApi.SignicatPreProdPkg.PackagingEndPoint>, PP.Signicat.WebApi.SignicatPreProdPkg.PackagingEndPoint {
        
        public PackagingEndPointClient() {
        }
        
        public PackagingEndPointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PackagingEndPointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PackagingEndPointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PackagingEndPointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PP.Signicat.WebApi.SignicatPreProdPkg.createpackageResponse1 PP.Signicat.WebApi.SignicatPreProdPkg.PackagingEndPoint.createpackage(PP.Signicat.WebApi.SignicatPreProdPkg.createpackage request) {
            return base.Channel.createpackage(request);
        }
        
        public PP.Signicat.WebApi.SignicatPreProdPkg.createpackageresponse createpackage(PP.Signicat.WebApi.SignicatPreProdPkg.createpackagerequest createpackagerequest) {
            PP.Signicat.WebApi.SignicatPreProdPkg.createpackage inValue = new PP.Signicat.WebApi.SignicatPreProdPkg.createpackage();
            inValue.createpackagerequest = createpackagerequest;
            PP.Signicat.WebApi.SignicatPreProdPkg.createpackageResponse1 retVal = ((PP.Signicat.WebApi.SignicatPreProdPkg.PackagingEndPoint)(this)).createpackage(inValue);
            return retVal.createpackageresponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PP.Signicat.WebApi.SignicatPreProdPkg.createpackageResponse1> PP.Signicat.WebApi.SignicatPreProdPkg.PackagingEndPoint.createpackageAsync(PP.Signicat.WebApi.SignicatPreProdPkg.createpackage request) {
            return base.Channel.createpackageAsync(request);
        }
        
        public System.Threading.Tasks.Task<PP.Signicat.WebApi.SignicatPreProdPkg.createpackageResponse1> createpackageAsync(PP.Signicat.WebApi.SignicatPreProdPkg.createpackagerequest createpackagerequest) {
            PP.Signicat.WebApi.SignicatPreProdPkg.createpackage inValue = new PP.Signicat.WebApi.SignicatPreProdPkg.createpackage();
            inValue.createpackagerequest = createpackagerequest;
            return ((PP.Signicat.WebApi.SignicatPreProdPkg.PackagingEndPoint)(this)).createpackageAsync(inValue);
        }
    }
}
