//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordAddInSignicat.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceWordNb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceWordNb() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordAddInSignicat.Resources.ResourceWordNb", typeof(ResourceWordNb).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan ikke skape dokumentsignering: .
        /// </summary>
        internal static string cannotcreateinsignicat {
            get {
                return ResourceManager.GetString("cannotcreateinsignicat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan ikke skape notat i CRM: .
        /// </summary>
        internal static string cannotcreatenote {
            get {
                return ResourceManager.GetString("cannotcreatenote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan ikke finne oppføringen med søket: .
        /// </summary>
        internal static string cannotfindsearch {
            get {
                return ResourceManager.GetString("cannotfindsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke finne avsenderen. Vennligst åpne opp mailen og spefiser en avsender og sendt på nytt..
        /// </summary>
        internal static string cannotfindsender {
            get {
                return ResourceManager.GetString("cannotfindsender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke finne verdi på setting i CRM: .
        /// </summary>
        internal static string cannotfindsetting {
            get {
                return ResourceManager.GetString("cannotfindsetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke lagre dokumentet i SharePoint.
        /// </summary>
        internal static string cannotsavetosp {
            get {
                return ResourceManager.GetString("cannotsavetosp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Et dokument har blitt sendt til deg for signering, klikk på knappen for å signere: .
        /// </summary>
        internal static string clicktosign {
            get {
                return ResourceManager.GetString("clicktosign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hente data fra CRM.
        /// </summary>
        internal static string datafromcrm {
            get {
                return ResourceManager.GetString("datafromcrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumentet er lagret i SharePint..
        /// </summary>
        internal static string docsavedsp {
            get {
                return ResourceManager.GetString("docsavedsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokument til SharePoint.
        /// </summary>
        internal static string docsp {
            get {
                return ResourceManager.GetString("docsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumentet er sent til signering, besøk CRM for oppdateringer!.
        /// </summary>
        internal static string documentsent {
            get {
                return ResourceManager.GetString("documentsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumentet er sendt til signering..
        /// </summary>
        internal static string documentsentforsinging {
            get {
                return ResourceManager.GetString("documentsentforsinging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumentsignering.
        /// </summary>
        internal static string documentsinging {
            get {
                return ResourceManager.GetString("documentsinging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En feil har oppstått ved utsending av e-post: .
        /// </summary>
        internal static string emailerror {
            get {
                return ResourceManager.GetString("emailerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feil ved søk av mottaker..
        /// </summary>
        internal static string emailfindreciever {
            get {
                return ResourceManager.GetString("emailfindreciever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke finne oppføringen: .
        /// </summary>
        internal static string recordnotfound {
            get {
                return ResourceManager.GetString("recordnotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM har ikke en standard webside.
        /// </summary>
        internal static string spsitenotfound {
            get {
                return ResourceManager.GetString("spsitenotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Dokumentsigneringen vil ikke være knyttet noen oppføring!.
        /// </summary>
        internal static string unassociated {
            get {
                return ResourceManager.GetString("unassociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word malen er ikke bra konstruert, vennligst klikk hjelp for mer detaljer!.
        /// </summary>
        internal static string wordtemplaterror {
            get {
                return ResourceManager.GetString("wordtemplaterror", resourceCulture);
            }
        }
    }
}
