//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordAddInSignicat.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceWordEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceWordEn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordAddInSignicat.Resources.ResourceWordEn", typeof(ResourceWordEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create documentsigning: .
        /// </summary>
        internal static string cannotcreateinsignicat {
            get {
                return ResourceManager.GetString("cannotcreateinsignicat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create annotation in CRM:.
        /// </summary>
        internal static string cannotcreatenote {
            get {
                return ResourceManager.GetString("cannotcreatenote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the searched record in CRM: .
        /// </summary>
        internal static string cannotfindsearch {
            get {
                return ResourceManager.GetString("cannotfindsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender could not be found in CRM PP config! Please go to the email, specify a sender and resend again..
        /// </summary>
        internal static string cannotfindsender {
            get {
                return ResourceManager.GetString("cannotfindsender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the value in Settings in CRM: .
        /// </summary>
        internal static string cannotfindsetting {
            get {
                return ResourceManager.GetString("cannotfindsetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save document to SP..
        /// </summary>
        internal static string cannotsavetosp {
            get {
                return ResourceManager.GetString("cannotsavetosp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A document has been sent to you for sginature. Click on this link to sign:.
        /// </summary>
        internal static string clicktosign {
            get {
                return ResourceManager.GetString("clicktosign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting data from CRM.
        /// </summary>
        internal static string datafromcrm {
            get {
                return ResourceManager.GetString("datafromcrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document is saved in SharePoint..
        /// </summary>
        internal static string docsavedsp {
            get {
                return ResourceManager.GetString("docsavedsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document to SharePoint.
        /// </summary>
        internal static string docsp {
            get {
                return ResourceManager.GetString("docsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document is sent for signing, visit the log in CRM for updates!.
        /// </summary>
        internal static string documentsent {
            get {
                return ResourceManager.GetString("documentsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document is sent for signing..
        /// </summary>
        internal static string documentsentforsinging {
            get {
                return ResourceManager.GetString("documentsentforsinging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Signing.
        /// </summary>
        internal static string documentsinging {
            get {
                return ResourceManager.GetString("documentsinging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred in sending email: .
        /// </summary>
        internal static string emailerror {
            get {
                return ResourceManager.GetString("emailerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a record with number: .
        /// </summary>
        internal static string recordnotfound {
            get {
                return ResourceManager.GetString("recordnotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM does not have any default SharePoint Sites.
        /// </summary>
        internal static string spsitenotfound {
            get {
                return ResourceManager.GetString("spsitenotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . The signing package will not be connected to any record!.
        /// </summary>
        internal static string unassociated {
            get {
                return ResourceManager.GetString("unassociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Word template is not well constructed, please klikk help for more details!.
        /// </summary>
        internal static string wordtemplaterror {
            get {
                return ResourceManager.GetString("wordtemplaterror", resourceCulture);
            }
        }
    }
}
