//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP.Signicat.WebApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resourceeng {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resourceeng() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PP.Signicat.WebApi.Resources.Resourceeng", typeof(Resourceeng).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Shared/SignCallBack.cshtml.
        /// </summary>
        public static string callbackpage {
            get {
                return ResourceManager.GetString("callbackpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a copy of the signed document.
        /// </summary>
        public static string emaildescription {
            get {
                return ResourceManager.GetString("emaildescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy of signed document.
        /// </summary>
        public static string emailsubject {
            get {
                return ResourceManager.GetString("emailsubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merged document.
        /// </summary>
        public static string merged {
            get {
                return ResourceManager.GetString("merged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document is signed by using the Signicat technology..
        /// </summary>
        public static string notetext {
            get {
                return ResourceManager.GetString("notetext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents are waiting for you to sign, you have 2 days left! Please find the documents in the original email..
        /// </summary>
        public static string signicatexpiration {
            get {
                return ResourceManager.GetString("signicatexpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents has not been signed by the reciever.
        /// </summary>
        public static string signicatexpired {
            get {
                return ResourceManager.GetString("signicatexpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message from Signicat.
        /// </summary>
        public static string signicatmessage {
            get {
                return ResourceManager.GetString("signicatmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document signing has been rejected!.
        /// </summary>
        public static string signicatrejected {
            get {
                return ResourceManager.GetString("signicatrejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A document or more are signed and will be available in Dynamics 365 shortly!.
        /// </summary>
        public static string signicatsigned {
            get {
                return ResourceManager.GetString("signicatsigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single document.
        /// </summary>
        public static string singledocument {
            get {
                return ResourceManager.GetString("singledocument", resourceCulture);
            }
        }
    }
}
