//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP.Signicat.WebApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resourcenb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resourcenb() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PP.Signicat.WebApi.Resources.Resourcenb", typeof(Resourcenb).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Shared/SignCallBackNB.cshtml.
        /// </summary>
        public static string callbackpage {
            get {
                return ResourceManager.GetString("callbackpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hei, dette er en kopi av det signerte dokumentet.
        /// </summary>
        public static string emaildescription {
            get {
                return ResourceManager.GetString("emaildescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopi av det signerte dokumentet.
        /// </summary>
        public static string emailsubject {
            get {
                return ResourceManager.GetString("emailsubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sammenslått dokument.
        /// </summary>
        public static string merged {
            get {
                return ResourceManager.GetString("merged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dette dokumentet er signert ved bruk av Signicat teknologi..
        /// </summary>
        public static string notetext {
            get {
                return ResourceManager.GetString("notetext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singel dokument.
        /// </summary>
        public static string singledocument {
            get {
                return ResourceManager.GetString("singledocument", resourceCulture);
            }
        }
    }
}
